[package]
name = "proxy-re-encryption"
version = "0.1.0"
edition = "2021"

[lib]
name = "pre"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.10"
p256 = "0.13.2"
rand = "0.8.5"
sha2 = "0.10.8"
